### ISSUE TITLE
Week 1 - Task list and issues

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/pylyrics#1]
Reference Links:
[524 Milestone checklist](https://pages.github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/materials/assignments/milestone1.html) 
[Ref Repo from last year](https://github.com/UBC-MDS/pyhousehunter)

**General**
- [x] #4
- [x] pick a topic
- [ ] #3
- [ ] #2
- [x] #5
- [x] #6

**GitHub set-up**
- [x] #7
- [x] Manage issues - Macy

**README.md**
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #20

**Function specifications** (4 .py)
- [x] #14
- [x] #15
- [x] #16
- [x] #17

**Other files**
- [ ] #18
- [ ] #19

=======================Our functions=======================
1. Download the data
Input : url (csv) & col you wanna extract
Output : DataFrame with input cols

2. Extract lyrics from API
 Input : song_title[0], artist[0]
 Output : lyrics
Python API - https://pypi.org/project/lyricsgenius/
R API - https://ewenme.github.io/geniusr/

 3. Clear text
 Input : paragraph, list[voacb]
 Output : cleaned paragraph

 4. Plot WordCloud
 Input: song_title[], artist[]
 Const: Min 1; Max 5
 make use of (2) & (3)
 Output : A WordCloud

**Comment by artanzand** [comment]
I have added the usage for README.md

**Comment by artanzand** [comment]
We will be targeting to finish our tasks for 1300 (PST) on Friday, Jan 14 and have our pull requests. We can then do the reviews, adjustments between then and 1900 (PST) to finalize the 1st milestone submission.
