### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by nafi007** [UBC-MDS/pylyrics#39]
CONTRIBUTING.md file: you need to tell a potential user exactly the steps they need to do to edit your project. You need to give them specific instructions like forking the repo, then cloning to their local machine, pushing to a branch, submitting a pull request etc.  This bumped your "Create project structure for the Python project: Mechanics" grade down by 1 level. Everything else looks great!

**Comment by MacyChan** [comment]
Added the recommended instruction to CONTRIBUTING.md! Thank you!
