### ISSUE TITLE
License Discussion - Is MIT good?

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/pylyrics#73]
Hi Guys, we are using [MIT license](https://github.com/UBC-MDS/pylyrics/blob/main/LICENSE). 
Would like to initial a discussion about what license is better to be used.
Started a conversation on our [R Package](https://github.com/UBC-MDS/rlyrics/issues/49)
Let's discuss over there!

**Comment by artanzand** [comment]
Sounds good! we will continue the discussion over there.

**Comment by artanzand** [comment]
We had the discussion in the rlyrics package and decided to with MIT license.
